#!/usr/bin/env bash
set -euo pipefail

DEST=src/infrastructure/firebaseConfig.ts
EXAMPLE=src/infrastructure/firebaseConfig.example.ts

echo "Generating $DEST from environment (if present) or copying example..."

if [ -n "${FIREBASE_API_KEY-}" ]; then
  cat > "$DEST" <<EOF
// Auto-generated by prebuild script. Safe to overwrite in CI.
const firebaseConfig = {
  apiKey: '${FIREBASE_API_KEY}',
  authDomain: '${FIREBASE_AUTH_DOMAIN:-}',
  projectId: '${FIREBASE_PROJECT_ID:-}',
  storageBucket: '${FIREBASE_STORAGE_BUCKET:-}',
  messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID:-}',
  appId: '${FIREBASE_APP_ID:-}',
  measurementId: '${FIREBASE_MEASUREMENT_ID:-}'
};

export default firebaseConfig;
EOF
else
  echo "FIREBASE_API_KEY not set; copying example to $DEST"
  cp "$EXAMPLE" "$DEST"
fi

echo "Done"
